name: stablediffuser
channels:
  - sclare
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python>=3.10
  - pip
  - cudatoolkit #=11.3
  - pytorch # =1.13.1
  - pytorch-cuda=11.6
  - torchvision # =0.13.1
#  - numpy>=1.23
  - transformers=4.19.2
  - accelerate=0.12.0
  - gradio=3.16.2
  - numpy>=1.23
  - opencv # dep
  - future # dep
  - addict # dep
  - python-lmdb # dep
  - deprecation # dep
  - aenum # dep
  - yapf # dep
  - facexlib # dep
  # - requests # dep
  - trampoline # dep
  - boltons # dep
  # - idna # dep
  # - chardet # dep
  - filterpy # dep
  - numba # dep
  - llvmlite # dep
  - Pillow=9.4.0 
  - omegaconf=2.2.3
  - pytorch-lightning=1.7.6
  - scikit-image=0.19.2
  - timm=0.6.7
  - piexif=1.1.3 
  - einops=0.4.1
  - jsonmerge=1.8.0
  - kornia=0.6.7
  - lark=1.1.2
  - inflection=0.5.1
  - GitPython=3.1.27
  - safetensors>=0.2  # version 0.2.7
  - httpcore<=0.15
  - pip:
    - blendmodes==2022 # pip
    - basicsr==1.4.2 # pip
    - gfpgan==1.3.8 # pip
    - realesrgan==0.3.0 # pip
    # - torch
    - fonts # pip
    - font-roboto # pip
    - clean-fid==0.1.29 # pip
    - resize-right==0.0.2 # pip
    - torchdiffeq==0.2.3 # pip
    - fairscale==0.4.9 # pip
    - torchsde==0.2.5 # pip